### ISSUE TITLE
[pom] Remove the `maven-release-plugin` in the `build` section.

### ISSUE THREAD

**Issue by Naoghuman** [Naoghuman/lib-tile#13]
[pom] Remove the `maven-release-plugin` in the `build` section.
* The plugin isn't needed, because per default the naming from the jar file is okay.

**Comment by Yogendra0Sharma** [comment]
@Naoghuman: Hello Can I pick this issue. if we remove the plugin section (maven-release-plugin) then how target plugins generated?

**Comment by Naoghuman** [comment]
@Yogendra0Sharma 
Hi, I am not sure if I understand your question right (I am not native english speaker). But here is what I thing to understand :) .

My plan for the usage from the `maven-release-plugin` was originally to tweak the name from the output jar so I can upload my artifacts to `Maven Central` with the specific naming format `${project.artifactId}-${project.version}`. Through accident I find out that the configuration in the section from the `maven-release-plugin` wasn't be used in my IDE (NetBeans). I dig a little in internet and find following out:
* At >= 3.0.0 from Maven there is a new flag in the `<build>` section -> `<finalName>`. This flag allowed to tweak the output name from the jar which have as a default value `${artifactId}-${version}`.
* When I tweak the output with this flag then the generated jar has the new name, but the generated folder in `.me` is furthermore the default value.
* So for my `requirement` I don't need the plugin because I have via default the right output.

But the `maven-release-plugin` have much more tasks. I don't know for what you use the plugin in your pom? But if you used the different tasks to managed the single step manually or for the configuration in a automatically build then I think you will needed the plugin furthermore.

Answers this your question? If not plz ask again which more informations what you exactly mean :) .
